services:
  - type: web
    name: agriconnect-backend
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /actuator/health
    plan: free
    envVars:
      - key: PORT
        value: "8080"
      - key: DB_DRIVER
        value: org.postgresql.Driver
      - key: JPA_DIALECT
        value: org.hibernate.dialect.PostgreSQLDialect
      - key: JPA_DDL_AUTO
        value: update
      - key: JPA_SHOW_SQL
        value: "false"
      - key: JWT_ACCESS_MINUTES
        value: "120"
      - key: JWT_REFRESH_DAYS
        value: "14"
      - key: DB_URL
        value: jdbc:postgresql://db.arfamjwpxqroakimkflm.supabase.co:5432/postgres?sslmode=require
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: ADMIN_DEFAULT_EMAIL
        sync: false
      - key: ADMIN_DEFAULT_PASSWORD
        sync: false
