services:
  - type: web
    name: agriconnect-backend
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /actuator/health
    plan: free
    envVars:
      - key: PORT
        value: "8080"
      - key: DB_DRIVER
        value: org.h2.Driver
      - key: JPA_DIALECT
        value: org.hibernate.dialect.H2Dialect
      - key: JPA_DDL_AUTO
        value: update
      - key: JPA_SHOW_SQL
        value: "false"
      - key: JWT_ACCESS_MINUTES
        value: "120"
      - key: JWT_REFRESH_DAYS
        value: "14"
      - key: DB_URL
        value: jdbc:h2:mem:agriconnect_db;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
      - key: DB_USERNAME
        value: sa
      - key: DB_PASSWORD
        value: ""
      - key: JWT_SECRET
        value: AgriConnectSupabaseJWTSecretKey2026!Secure
      - key: FRONTEND_URL
        value: https://agri-connect-two-eta.vercel.app
      - key: ADMIN_DEFAULT_EMAIL
        value: admin@agriconnect.local
      - key: ADMIN_DEFAULT_PASSWORD
        value: Admin@12345
